require "./handlers/lifecycle"
require "./handlers/text_sync"
require "./handlers/definition_snippet"
require "./handlers/hover"
require "./handlers/definition"
require "./handlers/type_definition"
require "./handlers/implementation"
require "./handlers/formatting"
require "./handlers/range_formatting"
require "./handlers/on_type_formatting"
require "./handlers/document_symbol"
require "./handlers/completion"
require "./handlers/diagnostics"
require "./handlers/pull_diagnostics"
require "./handlers/semantic_tokens"
require "./handlers/folding_range"
require "./handlers/workspace_symbol"
require "./handlers/document_link"
require "./handlers/document_highlight"
require "./handlers/signature_help"
require "./handlers/inlay_hints"
require "./handlers/references"
require "./handlers/rename"
require "./handlers/prepare_rename"
require "./handlers/selection_range"
require "./handlers/organize_imports"
require "./handlers/will_save"
require "./handlers/code_action"
require "./handlers/code_lens"
require "./handlers/call_hierarchy"
require "./handlers/type_hierarchy"
require "./handlers/workspace_changes"

module CrystalLanguageServer
  module Handlers
  end
end
